"""initial schema

Revision ID: fece58ab524a
Revises: 
Create Date: 2026-07-28 19:31:14.295561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fece58ab524a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('marca', sa.String(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('supermercado', sa.String(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unidad_medida', sa.String(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_producto')
    )
    op.create_index(op.f('ix_productos_id_producto'), 'productos', ['id_producto'], unique=False)
    op.create_table('roles',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_roles_id_rol'), 'roles', ['id_rol'], unique=False)
    op.create_table('users',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(), nullable=False),
    sa.Column('nombre_completo', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('contrasena', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('proveedor_auth', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id_usuario'), 'users', ['id_usuario'], unique=False)
    op.create_index(op.f('ix_users_nombre_usuario'), 'users', ['nombre_usuario'], unique=True)
    op.create_table('configuracion_bot_externo',
    sa.Column('id_configuracion', sa.Integer(), nullable=False),
    sa.Column('plataforma', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_configuracion'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_configuracion_bot_externo_id_configuracion'), 'configuracion_bot_externo', ['id_configuracion'], unique=False)
    op.create_table('external_bot_link_codes',
    sa.Column('id_codigo', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=16), nullable=False),
    sa.Column('plataforma', sa.String(length=32), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_expiracion', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_codigo')
    )
    op.create_index(op.f('ix_external_bot_link_codes_codigo'), 'external_bot_link_codes', ['codigo'], unique=True)
    op.create_index(op.f('ix_external_bot_link_codes_id_codigo'), 'external_bot_link_codes', ['id_codigo'], unique=False)
    op.create_table('external_bot_sessions',
    sa.Column('id_sesion_bot', sa.Integer(), nullable=False),
    sa.Column('plataforma', sa.String(length=32), nullable=False),
    sa.Column('external_user_id', sa.String(length=128), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('estado_conversacion', sa.String(length=64), nullable=False),
    sa.Column('datos_temporales', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_sesion_bot'),
    sa.UniqueConstraint('plataforma', 'external_user_id', name='uq_external_bot_session_platform_user')
    )
    op.create_index(op.f('ix_external_bot_sessions_external_user_id'), 'external_bot_sessions', ['external_user_id'], unique=False)
    op.create_index(op.f('ix_external_bot_sessions_id_sesion_bot'), 'external_bot_sessions', ['id_sesion_bot'], unique=False)
    op.create_table('listas_compra',
    sa.Column('id_lista', sa.Integer(), nullable=False),
    sa.Column('nombre_lista', sa.String(), nullable=False),
    sa.Column('compartida', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=False),
    sa.Column('total_estimado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_lista')
    )
    op.create_index(op.f('ix_listas_compra_id_lista'), 'listas_compra', ['id_lista'], unique=False)
    op.create_table('preferencias_usuario',
    sa.Column('id_preferencia', sa.Integer(), nullable=False),
    sa.Column('idioma', sa.String(length=10), nullable=False),
    sa.Column('modo_oscuro', sa.Boolean(), nullable=False),
    sa.Column('notificaciones', sa.Boolean(), nullable=False),
    sa.Column('unidad_peso', sa.String(length=10), nullable=False),
    sa.Column('unidad_precio', sa.String(length=10), nullable=False),
    sa.Column('supermercado_favorito', sa.String(length=100), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_preferencia')
    )
    op.create_index(op.f('ix_preferencias_usuario_id_preferencia'), 'preferencias_usuario', ['id_preferencia'], unique=False)
    op.create_index(op.f('ix_preferencias_usuario_usuario_id'), 'preferencias_usuario', ['usuario_id'], unique=True)
    op.create_table('seguimientos_usuario',
    sa.Column('id_seguimiento', sa.Integer(), nullable=False),
    sa.Column('seguidor_id', sa.Integer(), nullable=False),
    sa.Column('seguido_id', sa.Integer(), nullable=False),
    sa.Column('fecha_seguimiento', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['seguido_id'], ['users.id_usuario'], ),
    sa.ForeignKeyConstraint(['seguidor_id'], ['users.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_seguimiento'),
    sa.UniqueConstraint('seguidor_id', 'seguido_id', name='uq_seguidor_seguido')
    )
    op.create_index(op.f('ix_seguimientos_usuario_id_seguimiento'), 'seguimientos_usuario', ['id_seguimiento'], unique=False)
    op.create_table('sesiones_autenticacion',
    sa.Column('id_sesion', sa.Integer(), nullable=False),
    sa.Column('proveedor', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_sesion'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_sesiones_autenticacion_id_sesion'), 'sesiones_autenticacion', ['id_sesion'], unique=False)
    op.create_table('solicitudes_baja_usuario',
    sa.Column('id_solicitud', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=False),
    sa.Column('fecha_resolucion', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_solicitud')
    )
    op.create_index(op.f('ix_solicitudes_baja_usuario_id_solicitud'), 'solicitudes_baja_usuario', ['id_solicitud'], unique=False)
    op.create_table('solicitudes_seguimiento',
    sa.Column('id_solicitud_seguimiento', sa.Integer(), nullable=False),
    sa.Column('solicitante_id', sa.Integer(), nullable=False),
    sa.Column('destinatario_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['destinatario_id'], ['users.id_usuario'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['users.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_solicitud_seguimiento'),
    sa.UniqueConstraint('solicitante_id', 'destinatario_id', name='uq_solicitud_seguimiento')
    )
    op.create_index(op.f('ix_solicitudes_seguimiento_id_solicitud_seguimiento'), 'solicitudes_seguimiento', ['id_solicitud_seguimiento'], unique=False)
    op.create_table('external_bot_messages',
    sa.Column('id_mensaje_bot', sa.Integer(), nullable=False),
    sa.Column('direccion', sa.String(length=16), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('sesion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sesion_id'], ['external_bot_sessions.id_sesion_bot'], ),
    sa.PrimaryKeyConstraint('id_mensaje_bot')
    )
    op.create_index(op.f('ix_external_bot_messages_id_mensaje_bot'), 'external_bot_messages', ['id_mensaje_bot'], unique=False)
    op.create_table('historial_listas',
    sa.Column('id_historial', sa.Integer(), nullable=False),
    sa.Column('nombre_lista', sa.String(length=255), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('num_productos', sa.Integer(), nullable=False),
    sa.Column('total_gastado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('lista_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lista_id'], ['listas_compra.id_lista'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_historial')
    )
    op.create_index(op.f('ix_historial_listas_id_historial'), 'historial_listas', ['id_historial'], unique=False)
    op.create_table('list_chat_messages',
    sa.Column('id_chat_message', sa.Integer(), nullable=False),
    sa.Column('lista_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=80), nullable=True),
    sa.Column('suggestions_json', sa.JSON(), nullable=False),
    sa.Column('context_summary_json', sa.JSON(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lista_id'], ['listas_compra.id_lista'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_chat_message')
    )
    op.create_index(op.f('ix_list_chat_messages_id_chat_message'), 'list_chat_messages', ['id_chat_message'], unique=False)
    op.create_index(op.f('ix_list_chat_messages_lista_id'), 'list_chat_messages', ['lista_id'], unique=False)
    op.create_index(op.f('ix_list_chat_messages_usuario_id'), 'list_chat_messages', ['usuario_id'], unique=False)
    op.create_table('listas_compartidas',
    sa.Column('id_lista_compartida', sa.Integer(), nullable=False),
    sa.Column('lista_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo_compartido', sa.String(length=20), nullable=False),
    sa.Column('fecha_compartida', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lista_id'], ['listas_compra.id_lista'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_lista_compartida'),
    sa.UniqueConstraint('lista_id', 'usuario_id', name='uq_lista_usuario_compartida')
    )
    op.create_index(op.f('ix_listas_compartidas_id_lista_compartida'), 'listas_compartidas', ['id_lista_compartida'], unique=False)
    op.create_table('productos_lista',
    sa.Column('id_producto_lista', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_estimado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('lista_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lista_id'], ['listas_compra.id_lista'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_producto_lista')
    )
    op.create_index(op.f('ix_productos_lista_id_producto_lista'), 'productos_lista', ['id_producto_lista'], unique=False)
    op.create_table('historial_productos_lista',
    sa.Column('id_historial_producto', sa.Integer(), nullable=False),
    sa.Column('historial_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('nombre_producto', sa.String(), nullable=False),
    sa.Column('marca', sa.String(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('supermercado', sa.String(), nullable=False),
    sa.Column('unidad_medida', sa.String(), nullable=True),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_estimado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['historial_id'], ['historial_listas.id_historial'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_historial_producto')
    )
    op.create_index(op.f('ix_historial_productos_lista_id_historial_producto'), 'historial_productos_lista', ['id_historial_producto'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historial_productos_lista_id_historial_producto'), table_name='historial_productos_lista')
    op.drop_table('historial_productos_lista')
    op.drop_index(op.f('ix_productos_lista_id_producto_lista'), table_name='productos_lista')
    op.drop_table('productos_lista')
    op.drop_index(op.f('ix_listas_compartidas_id_lista_compartida'), table_name='listas_compartidas')
    op.drop_table('listas_compartidas')
    op.drop_index(op.f('ix_list_chat_messages_usuario_id'), table_name='list_chat_messages')
    op.drop_index(op.f('ix_list_chat_messages_lista_id'), table_name='list_chat_messages')
    op.drop_index(op.f('ix_list_chat_messages_id_chat_message'), table_name='list_chat_messages')
    op.drop_table('list_chat_messages')
    op.drop_index(op.f('ix_historial_listas_id_historial'), table_name='historial_listas')
    op.drop_table('historial_listas')
    op.drop_index(op.f('ix_external_bot_messages_id_mensaje_bot'), table_name='external_bot_messages')
    op.drop_table('external_bot_messages')
    op.drop_index(op.f('ix_solicitudes_seguimiento_id_solicitud_seguimiento'), table_name='solicitudes_seguimiento')
    op.drop_table('solicitudes_seguimiento')
    op.drop_index(op.f('ix_solicitudes_baja_usuario_id_solicitud'), table_name='solicitudes_baja_usuario')
    op.drop_table('solicitudes_baja_usuario')
    op.drop_index(op.f('ix_sesiones_autenticacion_id_sesion'), table_name='sesiones_autenticacion')
    op.drop_table('sesiones_autenticacion')
    op.drop_index(op.f('ix_seguimientos_usuario_id_seguimiento'), table_name='seguimientos_usuario')
    op.drop_table('seguimientos_usuario')
    op.drop_index(op.f('ix_preferencias_usuario_usuario_id'), table_name='preferencias_usuario')
    op.drop_index(op.f('ix_preferencias_usuario_id_preferencia'), table_name='preferencias_usuario')
    op.drop_table('preferencias_usuario')
    op.drop_index(op.f('ix_listas_compra_id_lista'), table_name='listas_compra')
    op.drop_table('listas_compra')
    op.drop_index(op.f('ix_external_bot_sessions_id_sesion_bot'), table_name='external_bot_sessions')
    op.drop_index(op.f('ix_external_bot_sessions_external_user_id'), table_name='external_bot_sessions')
    op.drop_table('external_bot_sessions')
    op.drop_index(op.f('ix_external_bot_link_codes_id_codigo'), table_name='external_bot_link_codes')
    op.drop_index(op.f('ix_external_bot_link_codes_codigo'), table_name='external_bot_link_codes')
    op.drop_table('external_bot_link_codes')
    op.drop_index(op.f('ix_configuracion_bot_externo_id_configuracion'), table_name='configuracion_bot_externo')
    op.drop_table('configuracion_bot_externo')
    op.drop_index(op.f('ix_users_nombre_usuario'), table_name='users')
    op.drop_index(op.f('ix_users_id_usuario'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_id_rol'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_productos_id_producto'), table_name='productos')
    op.drop_table('productos')
    # ### end Alembic commands ###
