export const GOOGLE_WEB_CLIENT_ID = "PON_AQUI_TU_GOOGLE_WEB_CLIENT_ID";
export const GOOGLE_ANDROID_CLIENT_ID = "PON_AQUI_TU_GOOGLE_ANDROID_CLIENT_ID";
export const GOOGLE_IOS_CLIENT_ID = "PON_AQUI_TU_GOOGLE_IOS_CLIENT_ID";